[project]
name = "auditora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KadriSof", email = "ms.kadri.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
auditora = "auditora:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
